import OpenAI from 'openai';

const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
const model=process.env.LLM_MODEL||'gpt-4o-mini';
const system=`You are CareVoice, an empathetic preliminary health-intake voice assistant. You are NOT a doctor and must not diagnose or prescribe. Collect the patient's name, main concern/symptom, duration/onset, severity, and related symptoms. Ask ONE question at a time. Adapt to the user's answers and never repeat information already captured. If an answer is vague, ask one short clarifying follow-up. Use simple English or Hindi depending on the language used by the user. Keep spoken responses to 1-2 short sentences. If an emergency red-flag symptom is described, recommend seeking appropriate urgent medical care without diagnosing.`;
export async function transcribe(buffer:Buffer){const result=await client.audio.transcriptions.create({file:await OpenAI.toFile(buffer,'audio.webm'),model:process.env.STT_MODEL||'gpt-4o-mini-transcribe',response_format:'text'});return String(result)}
export async function respond(history:{role:'user'|'assistant';content:string}[]){const r=await client.responses.create({model,input:[{role:'system',content:system},...history.map(x=>({role:x.role,content:x.content}))]});return r.output_text.trim()}
export async function speak(text:string){const r=await client.audio.speech.create({model:process.env.TTS_MODEL||'tts-1',voice:process.env.TTS_VOICE||'alloy',input:text,response_format:'mp3'});return Buffer.from(await r.arrayBuffer()).toString('base64')}
export async function report(history:{role:'user'|'assistant';content:string}[]){const prompt=`Create a concise health intake report from this conversation. Return ONLY valid JSON with keys: patientName (string), chiefComplaint (string), duration (string), severity (string), associatedSymptoms (string[]), followUp (string), redFlags (string[]), limitations (string). Do not invent missing facts. If the call was incomplete, say so in limitations. This is a screening summary, not a diagnosis.\nConversation:\n${history.map(x=>`${x.role.toUpperCase()}: ${x.content}`).join('\n')}`;const r=await client.responses.create({model,input:prompt});const raw=r.output_text.trim().replace(/^```json\s*/,'').replace(/\s*```$/,'');try{return JSON.parse(raw)}catch{return {patientName:'Not captured',chiefComplaint:'Not captured',duration:'Not captured',severity:'Not captured',associatedSymptoms:[],followUp:'Review the available information with a qualified healthcare professional.',redFlags:[],limitations:'The call ended before enough structured information could be captured.'}}}
