import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Activity, ArrowRight, Check, CheckCircle2, CircleStop, FileText, HeartPulse, Menu, Mic, Phone, ShieldCheck, Sparkles, Stethoscope, Volume2, X } from 'lucide-react';

type Turn={role:'assistant'|'user';text:string};
type Report={patientName:string;chiefComplaint:string;duration:string;severity:string;associatedSymptoms:string[];followUp:string;redFlags:string[];limitations:string};
const WS_URL=import.meta.env.VITE_WS_URL||'ws://localhost:8080';

export default function App(){
 const [calling,setCalling]=useState(false),[processing,setProcessing]=useState(false),[status,setStatus]=useState('Ready to start'),[turns,setTurns]=useState<Turn[]>([]),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[recording,setRecording]=useState(false),[input,setInput]=useState(''),[menu,setMenu]=useState(false);
 const ws=useRef<WebSocket|null>(null); const recorder=useRef<MediaRecorder|null>(null); const chunks=useRef<Blob[]>([]); const audio=useRef<HTMLAudioElement|null>(null);
 const connect=()=>{if(ws.current?.readyState===WebSocket.OPEN)return;const socket=new WebSocket(WS_URL);ws.current=socket;socket.onopen=()=>setStatus('Connected');socket.onclose=()=>{if(calling)setStatus('Disconnected')};socket.onerror=()=>setError('Could not connect to the voice server.');socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.event==='STATUS')setStatus(m.data);if(m.event==='AGENT_TEXT'){setTurns(t=>[...t,{role:'assistant',text:m.text}]);setProcessing(false);setStatus('Listening')}if(m.event==='AGENT_AUDIO'){const a=new Audio(`data:audio/mp3;base64,${m.audio}`);audio.current=a;a.onended=()=>setStatus('Listening');a.play().catch(()=>{});setStatus('Speaking')}if(m.event==='TRANSCRIPT_UPDATE'){setTurns(t=>[...t,{role:'user',text:m.text}])}if(m.event==='FINAL_REPORT'){setReport(m.report);setCalling(false);setRecording(false);setProcessing(false);setStatus('Call complete')}if(m.event==='ERROR'){setError(m.message);setProcessing(false);setStatus('Listening')}}};
 const start=()=>{setError('');setReport(null);setTurns([]);setCalling(true);setProcessing(false);setStatus('Starting call');connect();setTimeout(()=>ws.current?.send(JSON.stringify({event:'START_CALL'})),250)};
 const end=()=>{stopRecording();setCalling(false);setProcessing(true);setStatus('Generating report');ws.current?.send(JSON.stringify({event:'END_CALL'}))};
 const startRecording=async()=>{if(!calling||processing||recording)return;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream,{mimeType:'audio/webm'});chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks.current,{type:'audio/webm'});ws.current?.send(await blob.arrayBuffer());setProcessing(true);setStatus('Thinking')};r.start();recorder.current=r;setRecording(true);setStatus('Listening')}catch{setError('Microphone permission is required. You can use the text box below as a fallback.')}};
 const stopRecording=()=>{if(recorder.current?.state==='recording'){recorder.current.stop();setRecording(false)}};
 const sendText=()=>{if(!input.trim()||!calling||processing)return;const text=input.trim();setInput('');setTurns(t=>[...t,{role:'user',text}]);ws.current?.send(JSON.stringify({event:'USER_TEXT',text}));setProcessing(true);setStatus('Thinking')};
 useEffect(()=>()=>ws.current?.close(),[]);
 if(report) return <div className="site"><Header menu={menu} setMenu={setMenu} onStart={start}/><main><ReportView report={report} onRestart={start}/></main><Footer/></div>;
 if(calling) return <div className="site"><Header menu={menu} setMenu={setMenu} onStart={start}/><main><CallView {...{turns,recording,processing,status,error,input,setInput,startRecording,stopRecording,sendText,end}}/></main><Footer/></div>;
 return <div className="site"><Header menu={menu} setMenu={setMenu} onStart={start}/><main><Landing onStart={start}/></main><Footer/></div>;
}

function Header({menu,setMenu,onStart}:{menu:boolean;setMenu:(v:boolean)=>void;onStart:()=>void}){return <header className="nav"><a className="brand" href="#home"><span className="brand-mark"><HeartPulse size={18}/></span><span>Care<span>Voice</span></span></a><nav className={menu?'open':''}><a href="#home">Home</a><a href="#about">About</a><a href="#how">How it works</a><a href="#report">Report</a><a href="#contact">Contact</a></nav><button className="nav-cta" onClick={onStart}>Start a screening <ArrowRight size={15}/></button><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Menu"><Menu size={20}/></button></header>}

function Landing({onStart}:{onStart:()=>void}){return <>
 <section className="hero" id="home"><div className="shape shape-one"/><div className="shape shape-two"/><div className="hero-copy"><div className="eyebrow"><Sparkles size={13}/> AI-powered health intake</div><h1>A simple, calmer way to <span>start your health conversation.</span></h1><p>Talk naturally with an AI intake assistant. It asks focused questions, remembers your answers, and creates a clear summary when you're done.</p><div className="hero-actions"><button className="primary" onClick={onStart}><Phone size={18}/> Start a screening <ArrowRight size={17}/></button><a href="#how" className="text-link">See how it works <ArrowRight size={15}/></a></div><div className="mini-proof"><span><CheckCircle2 size={15}/> English + Hindi</span><span><CheckCircle2 size={15}/> Turn-by-turn voice</span><span><CheckCircle2 size={15}/> Structured report</span></div></div><div className="hero-art"><div className="hero-card"><div className="wave"><span/><span/><span/><span/><span/><span/><span/></div><div className="hero-icon"><Stethoscope size={42}/></div><b>Ready when you are</b><p>Start speaking and CareVoice will guide the intake one question at a time.</p><button onClick={onStart}>Begin conversation <ArrowRight size={15}/></button></div><div className="floating-card"><span className="live-dot"/> <b>Voice session</b><small>Secure · turn based</small></div></div></section>
 <section className="intro" id="about"><div className="intro-img"><div className="medical-illustration"><HeartPulse size={72}/><div className="pulse-line"/></div></div><div className="intro-copy"><div className="eyebrow">WHY CAREVOICE</div><h2>Designed to make the first few questions feel easier.</h2><p>The experience is intentionally simple: speak, listen, and answer. The assistant adapts when an answer is unclear instead of blindly reading a fixed script.</p><div className="feature-list"><Feature title="One question at a time" text="Short prompts keep the conversation natural and easy to follow." icon={<Mic size={18}/>}/><Feature title="Context-aware" text="The assistant keeps track of what has already been discussed." icon={<Activity size={18}/>}/><Feature title="Useful handoff" text="Your conversation becomes a concise structured health summary." icon={<FileText size={18}/>}/></div></div></section>
 <section className="how" id="how"><div className="section-heading"><div className="eyebrow">HOW IT WORKS</div><h2>From hello to a useful summary.</h2><p>A lightweight voice workflow built for a take-home demo — practical, responsive, and honest about its scope.</p></div><div className="steps"><Step n="01" title="Start the call" text="Allow microphone access and begin a voice intake session."/><Step n="02" title="Answer naturally" text="Speak in English or Hindi. Use the text fallback if needed."/><Step n="03" title="Get your report" text="End the call and receive a structured summary of what was captured."/></div></section>
 <section className="capture" id="report"><div className="section-heading"><div className="eyebrow">WHAT WE CAPTURE</div><h2>Only the essentials, organized clearly.</h2></div><div className="capture-grid"><Capture title="Main concern" text="What brings you here today?"/><Capture title="Duration" text="When did it start and how long has it been going on?"/><Capture title="Severity" text="How severe does it feel?"/><Capture title="Related symptoms" text="Anything else you have noticed."/></div></section>
 <section className="cta" id="contact"><div><div className="eyebrow">READY TO TALK?</div><h2>Start with a few simple questions.</h2><p>This is a preliminary screening experience, not a diagnosis or medical advice.</p></div><button className="primary light" onClick={onStart}>Start a screening <ArrowRight size={17}/></button></section>
 </>}
function Feature({title,text,icon}:{title:string;text:string;icon:ReactNode}){return <div className="feature"><span>{icon}</span><div><b>{title}</b><p>{text}</p></div></div>}
function Step({n,title,text}:{n:string;title:string;text:string}){return <article className="step"><strong>{n}</strong><h3>{title}</h3><p>{text}</p><a href="#home">Learn more <ArrowRight size={13}/></a></article>}
function Capture({title,text}:{title:string;text:string}){return <article className="capture-card"><div className="check"><Check size={14}/></div><div><b>{title}</b><p>{text}</p></div></article>}

function CallView({turns,recording,processing,status,error,input,setInput,startRecording,stopRecording,sendText,end}:{turns:Turn[];recording:boolean;processing:boolean;status:string;error:string;input:string;setInput:(v:string)=>void;startRecording:()=>void;stopRecording:()=>void;sendText:()=>void;end:()=>void}){return <section className="call-page"><div className="page-kicker"><span className="live-dot"/> LIVE HEALTH INTAKE <span>•</span> {status}</div><div className="call-head"><div><div className="eyebrow">VOICE SCREENING</div><h1>Let's start with <span>a few simple questions.</span></h1><p>Your AI intake assistant will ask one question at a time and keep track of the conversation.</p></div><button className="end-btn" onClick={end}><CircleStop size={17}/> End call</button></div><div className="call-layout"><div className="assistant-panel"><div className={`voice-orb ${recording?'recording':''} ${processing?'thinking':''}`}><div className="orb-ring"/><div className="orb-core"><HeartPulse size={42}/></div></div><h2>{processing?'Working on your answer…':recording?'Listening to you…':'Your AI intake assistant'}</h2><p>{recording?'Release the button when you finish speaking.':processing?'Please wait a moment while the next response is prepared.':'Press and hold the button to answer by voice.'}</p><button className={`hold-btn ${recording?'active':''}`} onMouseDown={startRecording} onMouseUp={stopRecording} onMouseLeave={stopRecording} onTouchStart={startRecording} onTouchEnd={stopRecording} disabled={processing}><Mic size={20}/>{recording?'Release to send':'Hold to speak'}</button><div className="divider"><span>or type your answer</span></div><div className="text-input"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendText()} placeholder="Type here…"/><button onClick={sendText} disabled={processing||!input.trim()}><ArrowRight size={17}/></button></div>{error&&<div className="error"><X size={15}/>{error}</div>}</div><div className="conversation"><div className="conversation-head"><div><span className="eyebrow">LIVE TRANSCRIPT</span><h3>Conversation</h3></div><Volume2 size={18}/></div><div className="message-list">{turns.length===0?<div className="empty"><HeartPulse size={22}/><p>Waiting for the assistant to greet you…</p></div>:turns.map((t,i)=><div className={`message ${t.role}`} key={i}><div className="message-avatar">{t.role==='assistant'?<HeartPulse size={13}/>:<Mic size={13}/>}</div><div><small>{t.role==='assistant'?'CareVoice':'You'}</small><p>{t.text}</p></div></div>)}</div></div></div></section>}

function ReportView({report,onRestart}:{report:Report;onRestart:()=>void}){return <section className="report-page"><div className="report-hero"><div><div className="eyebrow"><CheckCircle2 size={13}/> SCREENING COMPLETE</div><h1>A clear summary of <span>your conversation.</span></h1><p>Review the information that was captured during the intake. Missing details are intentionally left as not captured.</p></div><button className="secondary" onClick={onRestart}><Phone size={16}/> New screening</button></div><div className="report-cards"><div className="report-card"><div className="report-card-head"><div><span className="eyebrow">PATIENT</span><h3>{report.patientName||'Not captured'}</h3></div><div className="round-icon"><HeartPulse size={20}/></div></div><ReportItem label="Main concern" value={report.chiefComplaint}/><ReportItem label="Duration" value={report.duration}/><ReportItem label="Severity" value={report.severity}/></div><div className="report-card"><span className="eyebrow">KEY SYMPTOMS</span><h3>What was mentioned</h3>{report.associatedSymptoms?.length?<div className="chips">{report.associatedSymptoms.map((x,i)=><span key={i}>{x}</span>)}</div>:<p className="muted">No related symptoms were captured.</p>}<div className="report-note"><b>Follow-up</b><p>{report.followUp}</p></div>{report.redFlags?.length>0&&<div className="red-flags"><b>Worth following up on</b>{report.redFlags.map((x,i)=><p key={i}>• {x}</p>)}</div>}</div></div><div className="scope"><ShieldCheck size={18}/><div><b>Important scope</b><p>{report.limitations} CareVoice is a screening assistant and does not diagnose conditions or replace professional medical advice.</p></div></div></section>}
function ReportItem({label,value}:{label:string;value:string}){return <div className="report-item"><span>{label}</span><b>{value||'Not captured'}</b></div>}
function Footer(){return <footer id="footer"><div className="footer-top"><div><a className="brand footer-brand"><span className="brand-mark"><HeartPulse size={17}/></span><span>Care<span>Voice</span></span></a><p>A simple voice-first intake experience for preliminary health screening.</p></div><div><b>Explore</b><a href="#about">About</a><a href="#how">How it works</a><a href="#report">What we capture</a></div><div><b>Support</b><a href="#contact">Contact</a><a href="#home">Start screening</a><a href="#footer">Privacy</a></div><div><b>Disclaimer</b><p>This demo is not a diagnostic service. Seek urgent medical care for emergencies.</p></div></div><div className="footer-bottom">© 2026 CareVoice AI Health Intake · Built for demonstration purposes.</div></footer>}
